include: package:effective_dart/analysis_options.1.1.0.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    file_names: false
    public_member_api_docs: false
