name: advent_of_code
description: Dart solutions for the Advent of Code 2019.

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  equatable: ^1.0.0
  quiver: ^2.1.2+1

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
